FROM node:16.9.1-alpine

RUN apk add --no-cache alpine-conf && \
    setup-timezone -z Asia/Bangkok && \
    rm -rf /var/cache/apk/*

LABEL maintainer="Whalez Digital Teknologi"

WORKDIR /usr/apps/api-wilayah-indonesia

ENV NODE_ENV production

ENV TZ Asia/Jakarta

COPY package.json /usr/apps/api-wilayah-indonesia/

RUN yarn install && yarn global add knex@2.4.2 && yarn cache clean --all

COPY . /usr/apps/api-wilayah-indonesia

CMD ["yarn", "start:prod"]
