version: "3.9"

services:
  app:
    container_name: restful_api_wilayah_ind
    image: restful_api_wilayah_ind
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/var/www/app
      - /var/www/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: ["nodemon", "./bin/www"]
