version: "3.9"

services:
  app:
    container_name: restful_api_wilayah_ind
    image: restful_api_wilayah_ind
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
